### ISSUE TITLE
Move inline plugins into separate plugins

### ISSUE THREAD

**Issue by martinheidegger** [tradle/mycloud#34]
Currently several plugins are defined "inline" as opposed to plugin files that can be loaded on demand.
To make these plugins loadable (and have more control over the loading process) these plugins should be put into their own plugin files.

- [`keep-products-list-fresh`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L511-L534)
- [`style`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L501-L507)
- [`identity-publish`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L559-L601)
- [`limit-forms`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L613-L643)
- [`witness`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L644-L697)
- [`customize-message`](https://github.com/tradle/mycloud/blob/d86ae9103e479842c74b6438b1f39f50f74b3b7c/src/in-house-bot/index.ts#L704-L717)

**Comment by urbien** [comment]
above plugins can remain built in

**Comment by martinheidegger** [comment]
Having different systems how plugins work is not just mental load for the developer but also for the plugin loading process in general. For removing general complexity I think its a good idea to do this at some point.

**Comment by urbien** [comment]
theoretical point
in practice we need to prove the concept before starting to refactor 100 sources.
